### ISSUE TITLE
monitorer l'activité airflow

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/datagouvfr_data_pipelines#9]
Avoir des indicateurs permettant d'avoir une information synthétiques sur les traitements passés ces X dernières heures. Par exemple via une notification mattermost

**Comment by agarrone** [comment]
@Pierlou

**Comment by geoffreyaldebert** [comment]
Done in https://github.com/etalab/datagouvfr_data_pipelines/pull/58 https://github.com/etalab/datagouvfr_data_pipelines/pull/59 https://github.com/etalab/datagouvfr_data_pipelines/pull/60  https://github.com/etalab/datagouvfr_data_pipelines/pull/61
